/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-05-02 01:30:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class blink5_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"Coche-Control\" content=\"no-store\">\r\n");
      out.write("<link rel=\"icon\" href=\"faviconAlpha.png\"> \r\n");
      out.write("<title>blink4.jsp</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("	html {\r\n");
      out.write("		border : 10px solid gray;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	body {\r\n");
      out.write("		border : 10px solid blue;\r\n");
      out.write("	}\r\n");
      out.write("	table#table {\r\n");
      out.write("		border-collapse: collapse;\r\n");
      out.write("		border : 10px solid green;\r\n");
      out.write("	}\r\n");
      out.write("	td#td{ \r\n");
      out.write("		font-family :monospace;\r\n");
      out.write("		background : yellow;\r\n");
      out.write("	}\r\n");
      out.write("	td {\r\n");
      out.write("		font-family :monospace;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("class Color {\r\n");
      out.write("	static Black = \"blcak\";\r\n");
      out.write("    static Red	= \"red\";\r\n");
      out.write("    static Green = \"green\";\r\n");
      out.write("    static Yellow = \"yellow\";\r\n");
      out.write("    static Blue = \"blue\";\r\n");
      out.write("    static Magenta = \"magenta\";\r\n");
      out.write("    static Cyan = \"cyan\";\r\n");
      out.write("    static White = \"white\";\r\n");
      out.write("    \r\n");
      out.write("    static values() {\r\n");
      out.write("    	return [Color.Black, Color.Red, Color.Green, \r\n");
      out.write("    			Color.Yellow, Color.Blue, Color.Magenta,\r\n");
      out.write("    			Color.cyan, Color.white];\r\n");
      out.write("    };\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("class Alpha {\r\n");
      out.write("	constructor() {\r\n");
      out.write("		this.line = parseInt(Math.random()*20 + 1);\r\n");
      out.write("		this.column = parseInt(Math.random()*40 + 1);\r\n");
      out.write("		do {\r\n");
      out.write("			this.fg = Color.values()[parseInt(Math.random()*8)];\r\n");
      out.write("			this.bg = Color.values()[parseInt(Math.random()*8)];\r\n");
      out.write("		} while (this.fg===this.bg);\r\n");
      out.write("		this.ch = String.fromCharCode([parseInt(Math.random()*26+ 'A'.charCodeAt(0))] );\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	show() {\r\n");
      out.write("		let cell = table.rows[this.line-1].cells[this.column-1];\r\n");
      out.write("		cell.style.color = this.fg;\r\n");
      out.write("		cell.style.background = this.bg;\r\n");
      out.write("		cell.textContent = this.ch;\r\n");
      out.write("		cell.style.opacity = 1;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	hide() {\r\n");
      out.write("		let cell = table.rows[this.line-1].cells[this.column-1];\r\n");
      out.write("		cell.style.opacity = 0;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	isShow = true;\r\n");
      out.write("	blink() {\r\n");
      out.write("		if (this.isShow)\r\n");
      out.write("			this.show();\r\n");
      out.write("		else \r\n");
      out.write("			this.hide();\r\n");
      out.write("		\r\n");
      out.write("		this.isShow = !this.isShow;\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("class run() {\r\n");
      out.write("	hide();\r\n");
      out.write("	\r\n");
      out.write("	if (this.line==1 &&)\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("window.onload = function() {\r\n");
      out.write("	for (let i=0; i<50; i++) {\r\n");
      out.write("		let a = new Alpha();\r\n");
      out.write("		setInterval(() => {\r\n");
      out.write("			a.blink();\r\n");
      out.write("		}, Math.random()*200+10);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h1>Header</h1>\r\n");
      out.write("<table>\r\n");
      out.write("	<tbody>\r\n");
      out.write("		<tr><td>만든이</td><td>뽀로로</td></tr>\r\n");
      out.write("		<tr><td>작성일</td><td>2023/05/02</td></tr>\r\n");
      out.write("		<tr><td>과 목</td><td>HTML/CSS/JAVASCRIPT</td></tr>\r\n");
      out.write("	</tbody>	\r\n");
      out.write("	\r\n");
      out.write("</table>\r\n");
      out.write("<table id=\"table\">\r\n");
      out.write("	<tbody>\r\n");
      out.write("<!-- 	<tr><td>1</td><td>2</td></tr> -->\r\n");
      out.write("	");

		for (int i=0; i<20; i++) {
			out.print("<tr>");
			for (int j=0; j<40; j++) {
				out.print("<td id='td'; style='opacity: 0;'>");
				out.print((char)(Math.random()*26+ 'A'));
				out.print("</td>");
			}
			out.print("</tr>");
		}
	
	
      out.write("\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
